[package]

name = "parsimonious"
version = "0.0.1"
authors = [ "Alan Jeffrey <ajeffrey@mozilla.com>" ]

description = "Parsimonious parser combinators"
repository = "https://github.com/asajeffrey/parsimonious"
readme = "README.md"
keywords = [ "parsing", "parser combinators" ]
license = "MPL-2.0"
